---
title: "Benchmark detection of de novo assembled contigs"
output: html_notebook
---

load packages

```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tidyr)
library(rprojroot)
library(vegan)
library(ggpubr)
library(rstatix)
library(cowplot)

```


set paths and filenames

```{r}
### files
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv",
                   find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv",
                       find_rstudio_root_file())

de_novo_file=sprintf("%s/data/shuf100_TGVG_clustered_virus_contigs.tsv", 
                        find_rstudio_root_file())

marker_magu_features=sprintf("%s/data/Marker-MAGu_virus_DB_v1.1_metadata.tsv",
                             find_rstudio_root_file())

```


```{r}

de_novo_dt <- fread(de_novo_file, header = F, sep = "\t", 
                    col.names = c("sample_ID", "de_novo_contig", "TGVG_id",
                                  "n_alignments", "ANI", "qcov", "tcov"))

long_dt <- fread(sprintf("%s", long_table), sep = "\t", header = T) %>%
  select(sampleID, rel_abundance, lineage) %>%
  mutate(sampleID = as.character(sampleID),
         kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                             grepl("k__Vir", lineage) ~ "Virus",
                             grepl("k__Ar", lineage) ~ "Archea",
                             grepl("k__Euk", lineage) ~ "Eukaryota",
                             TRUE ~ "other"),
         species = gsub(".*s__","s__", lineage))

mm_features_dt <- fread(marker_magu_features, header = T, sep = "\t")
```


```{r}
de_novo_f_dt <- merge(de_novo_dt, mm_features_dt,
                      by.x = "TGVG_id", by.y = "contig_id") %>%
  rename(sampleID = sample_ID) %>%
  mutate(sampleID = as.character(sampleID),
         lineage = gsub("s__vSGB", "s__vOTU", lineage),
         species = gsub(".*s__","s__", lineage)) %>%
  filter(`marker-magu_genes` >= 4)
```

```{r}
subsample_dt <- long_dt %>%
  filter(sampleID %in% unique(de_novo_f_dt$sampleID)) 
```

```{r}
match_dt <- merge(long_dt, de_novo_f_dt,
      by = c("sampleID", "species"),
      all.y = T) %>%
  select(c(sampleID, rel_abundance, species, `marker-magu_genes`))
```




