---
title: "Analyze relationship between bacteria SGBs and virus SGBs per sample and read #, TEDDY data"
output: html_notebook
---

load packages
```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tidyr)
library(rprojroot)
library(ggpubr)
library(rstatix)
```

set paths and filenames

```{r}
### files
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv",
                   find_rstudio_root_file())
read_table=sprintf("%s/data/mp142_TEDDY_marker_gene_detection_out1.reads_by_sample.tsv",
                   find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv",
                       find_rstudio_root_file())

```

load tables get counts of SGBs from each kingdom
```{r}
long_dt <- fread(sprintf("%s", long_table), sep = "\t", header = T) %>%
  select(sampleID, rel_abundance, lineage) %>%
  mutate(kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                             grepl("k__Vir", lineage) ~ "Virus",
                             grepl("k__Ar", lineage) ~ "Archaea",
                             grepl("k__Euk", lineage) ~ "Eukaryota",
                             TRUE ~ "other"))

reads_dt <- fread(sprintf("%s", read_table), sep = "\t", header = T)

long_w_read_dt <- merge(long_dt, reads_dt, by = "sampleID")
```

```{r}
## load metadata table
meta_dt <- fread(sprintf("%s", metadata_table), sep = ",", header = T) %>%
  select(-V1)
meta_dt$sample <- as.character(meta_dt$sample)
```

Summarize kingdom-level relative abundance and read count, plot
```{r}
sum_dt <- long_w_read_dt %>%
  group_by(sampleID, kingdom) %>%
  filter(kingdom != "Eukaryota",
         kingdom != "Archaea") %>%
  summarize(n = n(),
            total_rel_abundance = sum(rel_abundance),
            Reads = first(filtered_reads)) %>%
  pivot_wider(names_from = kingdom, values_from = c(n, total_rel_abundance), values_fill = 0)

merge_dt <- merge(sum_dt, meta_dt,
                  by.x = "sampleID", by.y = "sample")
```


Basic correlation, # virus SGBS vs # bacteria SGBs
```{r}
vir_vs_bacp <- long_w_read_dt %>%
  group_by(sampleID, kingdom) %>%
  filter(kingdom != "Eukaryota",
         kingdom != "Archaea") %>%
  summarize(n = n(),
            total_rel_abundance = sum(rel_abundance),
            Reads = first(filtered_reads)) %>%
  pivot_wider(names_from = kingdom, values_from = c(n, total_rel_abundance), values_fill = 0) %>%
  #ggplot(aes(x = n_Bacteria, y = n_Virus, size = filtered_reads)) +
  #geom_point(alpha = 0.3, stroke = 0, color = "cornflowerblue", add = "reg.line") +
  ggscatter(x = "n_Bacteria", y = "n_Virus", size = "Reads", alpha = 0.2, 
            stroke = 0, color = "cornflowerblue", 
            add = "reg.line", add.params = list(color = "grey30")) +
  theme_bw() +
  stat_cor(label.x = 0, label.y = 150) +
  stat_regline_equation(label.x = 0, label.y = 130) +
  labs(x = "# of Detected Bacteria SGBs", y = "# of Detected Virus SGBs")
vir_vs_bacp

ggsave(vir_vs_bacp, 
       file = sprintf("%s/charts/virus_SGBs_vs_bacteria_SGBs_reads1.pdf", find_rstudio_root_file()), 
                 width = 4, height = 3)
```

```{r}
## Basic correlation, # virus SGBS vs # bacteria SGBs but with sample age
agep <- merge_dt %>%
  ggscatter(x = "n_Bacteria", y = "n_Virus", size = "Reads", alpha = 0.4, 
            stroke = 0, color = "age_days", 
            add = "reg.line", add.params = list(color = "grey30")) +
  theme_bw() +
  scale_color_gradient2(low = "yellow", mid = "purple", 
                        high = "grey10", midpoint = 1000, 
                        name ="day of life") +
  stat_cor(label.x = 0, label.y = 150) +
  stat_regline_equation(label.x = 0, label.y = 130) +
  labs(x = "# of Detected Bacteria SGBs", y = "# of Detected Virus SGBs")

agep

ggsave(agep, 
       file = sprintf("%s/charts/virus_SGBs_vs_bacteria_SGBs_reads1.agecolor.pdf", find_rstudio_root_file()), 
                 width = 5, height = 3.5)

## Basic correlation, # virus SGBS vs # bacteria SGBs but with read count
readp <- merge_dt %>%
  ggscatter(x = "n_Bacteria", y = "n_Virus", size = "Reads", alpha = 0.4, 
            stroke = 0, color = "Reads", 
            add = "reg.line", add.params = list(color = "grey30")) +
  theme_bw() +
  scale_color_gradient2(low = "turquoise", mid = "burlywood", 
                        high = "tomato4", midpoint = 1.8e7) +
  stat_cor(label.x = 0, label.y = 150) +
  stat_regline_equation(label.x = 0, label.y = 130) +
  labs(x = "# of Detected Bacteria SGBs", y = "# of Detected Virus SGBs")

readp

ggsave(readp, 
       file = sprintf("%s/charts/virus_SGBs_vs_bacteria_SGBs_reads1.readcolor.pdf", find_rstudio_root_file()), 
                 width = 5, height = 3.5)
```



ratio of virus SGB:bacteria SGB vs reads
```{r}

## virus to bacteria count ratio by reads
ratiop <- merge_dt %>%
  mutate(ratio = n_Virus / n_Bacteria) %>%
  filter(ratio < 10) %>%
  ggscatter(x = "Reads", y = "ratio", size = 4, alpha = 0.4, 
            stroke = 0, color = "age_days") +
  theme_bw() +
  scale_color_gradient2(low = "yellow", mid = "purple", 
                        high = "grey10", midpoint = 1000, 
                        name ="day of life") +
  stat_cor(label.x = 2e7, label.y = 6) +
  stat_regline_equation(label.x = 2e7, label.y = 5) +
  labs(x = "# of Reads", 
       y = "Ratio of \n(Virus SGBs:Bacteria SGBs)")

ratiop

ggsave(ratiop, 
       file = sprintf("%s/charts/ratio_virus_vs_bacteria.readcolor.pdf", find_rstudio_root_file()), 
                 width = 5, height = 3.5)


## virus to bacteria rel. abundance ratio by reads

rel_abp <- merge_dt %>%
  mutate(ratio = total_rel_abundance_Virus / total_rel_abundance_Bacteria) %>%
  filter(ratio < 10) %>%
  ggscatter(x = "Reads", y = "ratio", size = 4, alpha = 0.4, 
            stroke = 0, color = "age_days") +
  theme_bw() +
  scale_color_gradient2(low = "yellow", mid = "purple", 
                        high = "grey10", midpoint = 1000, 
                        name ="day of life") +
  stat_cor(label.x = 0, label.y = 9) +
  stat_regline_equation(label.x = 0, label.y = 8) +
  labs(x = "# of Reads", 
       y = "Ratio of \n(Virus rel. abundance:Bacteria rel. abundance)")

rel_abp
```


```{r}
## virus to bacteria count ratio by age
ratioagep <- merge_dt %>%
  mutate(ratio = n_Virus / n_Bacteria) %>%
  filter(ratio < 10) %>%
  ggscatter(x = "age_days", y = "ratio", size = 4, alpha = 0.4, 
            stroke = 0, color = "age_days") +
  theme_bw() +
  scale_color_gradient2(low = "yellow", mid = "purple", 
                        high = "grey10", midpoint = 1000, 
                        name ="day of life") +
  labs(x = "day of life", 
       y = "Ratio of \n(Virus SGBs:Bacteria SGBs)")

ratioagep
```

reads vs SGB count
```{r}

vir_readp <- merge_dt %>%
  ggscatter(x = "Reads", y = "n_Virus", size = 3, alpha = 0.4, 
            stroke = 0, color = "#F2AD00", 
            add = "reg.line", add.params = list(color = "grey30")) +
  theme_bw() +
  stat_cor(label.x = 0, label.y = 100) +
  stat_regline_equation(label.x = 0, label.y = 80) +
  labs(x = "# of Reads", y = "# of Detected Virus SGBs")

vir_readp

bac_readp <- merge_dt %>%
  ggscatter(x = "Reads", y = "n_Bacteria", size = 3, alpha = 0.4, 
            stroke = 0, color = "#5BBCD6", 
            add = "reg.line", add.params = list(color = "grey30")) +
  theme_bw() +
  stat_cor(label.x = 0, label.y = 100) +
  stat_regline_equation(label.x = 0, label.y = 80) +
  labs(x = "# of Reads", y = "# of Detected Bacteria SGBs")

bac_readp
```

boxplot
```{r}
round_any = function(x, accuracy, f=ceiling){f(x/ accuracy) * accuracy}

merge_dt %>%
  mutate(round_reads = round_any(Reads, 2000000)) %>%
  filter(round_reads <= 2.6e7) %>%
  ggplot(aes(x = factor(round_reads), y = n_Virus)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

merge_dt %>%
  mutate(round_reads = round_any(Reads, 2000000)) %>%
  filter(round_reads <= 2.6e7) %>%
  ggplot(aes(x = factor(round_reads), y = n_Bacteria)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  stat_compare_means(label = "p.signif")
```







