---
title: "intra-subject persistence for bacteria and virus SGBs"
output: html_notebook
---

load packages
```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tibble)
library(here)
library(rprojroot)
library(ggpubr)
library(rstatix)

```

set paths and filenames
```{r}
### files
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv",
                   find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv",
                       find_rstudio_root_file())

```


load long table and metadata, merge 
```{r}
long_dt <- fread(long_table, sep = "\t", header = T) %>%
  select(sampleID, rel_abundance, lineage) %>%
  mutate(kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                             grepl("k__Vir", lineage) ~ "Virus",
                             grepl("k__Ar", lineage) ~ "Archea",
                             grepl("k__Euk", lineage) ~ "Eukaryota",
                             TRUE ~ "other"))


meta_dt <- fread(metadata_table, sep = ",", header = T) %>%
  select(-V1)

mask_id_count <- meta_dt %>%
  group_by(mask_id) %>%
  filter(n() >= 10) %>%
  summarize(total_samples = n())

merge_dt <- merge(long_dt, meta_dt, by.x = "sampleID", by.y ="sample")

## here, intra-subject sample count per lineage/SGB is calculated
persist_dt <- merge_dt %>%
  group_by(lineage, kingdom, mask_id) %>%
  summarize(samples_detected = n())

persist_dt <- merge(persist_dt, mask_id_count, by = "mask_id") %>%
  mutate(frequency_detected = samples_detected/total_samples)

dim(
  persist_dt %>% distinct(mask_id)
)

```

calculate stats
```{r}
stat.test <- persist_dt %>% 
  filter(kingdom == "Virus" | kingdom == "Bacteria") %>%
  wilcox_test(frequency_detected ~ kingdom) %>%
  add_significance(p.col="p", output.col="p.signif")
stat.test <- stat.test %>% add_xy_position(x = "kingdom")
stat.test


```

plot violins
```{r}
persist_dt %>% 
  filter(kingdom == "Virus" | kingdom == "Bacteria") %>%
  ggplot(aes(factor(kingdom), frequency_detected)) + 
  geom_violin(aes(fill = factor(kingdom)),  
              alpha = 0.6, draw_quantiles = c(0.25, 0.75), 
              linetype = "dotted") +
  geom_violin(fill="transparent", draw_quantiles = c(0.5)) +
  theme_bw() + 
  xlab("") + 
  ylab("SGB Intra-subject Frequency") + 
  scale_fill_manual(values=c("#F2AD00", "#5BBCD6")) + 
  stat_pvalue_manual(stat.test, label = "p.signif", 
                     y.position = 1.05, tip.length = 0.01, 
                     coord.flip = TRUE)  + 
  coord_flip() +
  theme(legend.position = "none")

ggsave(sprintf("%s/charts/bacteria_vs_virus_SGB_intrasubject_frequency1.pdf",
               find_rstudio_root_file()), width = 4, height = 3)

## save stats table
stat.test <- as.data.frame(stat.test)
stat.test <- apply(stat.test,2,as.character)
write.csv(stat.test, 
          file=sprintf("%s/intermediate_files/wilcoxon_test_vOTU_bOTU_persist_10samps.csv",
                       find_rstudio_root_file()))
```









