---
title: "Compare relative abundance of different temporal subset taxa for T1D vs non-T1D subjects, NCC groups"
output: html_notebook
---

load packages

```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tidyr)
library(rprojroot)
library(vegan)
library(ggpubr)
library(rstatix)
library(cowplot)

```

set paths and filenames

```{r}
### files
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv",
                   find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv",
                       find_rstudio_root_file())
subset_table=sprintf("%s/intermediate_files/prev_SGBs_cluster_assignments_long_abundance.tsv",
                     find_rstudio_root_file())

T1D_groups_file=sprintf("%s/data/MP142_CASE_CNTRL_T1D_LIST1.csv", 
                        find_rstudio_root_file())

```

load long table and metadata, merge

```{r}
long_dt <- fread(sprintf("%s", long_table), sep = "\t", header = T) %>%
  select(sampleID, rel_abundance, lineage) %>%
  mutate(sampleID = as.character(sampleID),
         species = gsub(".*s__","s__", lineage ),
         kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                             grepl("k__Vir", lineage) ~ "Virus",
                             grepl("k__Ar", lineage) ~ "Archea",
                             grepl("k__Euk", lineage) ~ "Eukaryota",
                             TRUE ~ "other"))

meta_dt <- fread(sprintf("%s", metadata_table), sep = ",", header = T) %>%
  select(-V1) %>%
  mutate(sample = as.character(sample))


groups_dt <- fread(T1D_groups_file, sep = ",", header = T) %>%
  select(c(mask_id, case_ind))

merge_full_dt <- merge(long_dt, meta_dt, by.x = "sampleID", by.y ="sample")

## filtering down to only subject from TEDDY T1D groups

merge_dt <- merge(merge_full_dt, groups_dt, by = "mask_id") %>%
  distinct()

rm(merge_full_dt)

```

load temporal subset dt
```{r}
## this functions rounds a number up to the nearest 100
round_any = function(x, accuracy, f=ceiling){f(x/ accuracy) * accuracy}

temporal_sub_dt <- fread(sprintf("%s", subset_table), sep = "\t", header = T) %>%
  distinct(species, assignment)

prev_sub_dt <- merge(merge_dt, temporal_sub_dt, by = "species") %>%
  group_by(sampleID, assignment) %>%
  summarize(assign_rel_abund = sum(rel_abundance))

merge_prev_sub_dt <- merge(prev_sub_dt, meta_dt, by.x = "sampleID", by.y ="sample")

merge_prev_sub_dt <- merge(merge_prev_sub_dt, groups_dt, by = "mask_id") %>%
  distinct() %>%
  mutate(rounded_DOL =  round_any(age_days, 100)) %>%
  filter(rounded_DOL <= 1400)
```

wilcox test for DOL and temporal subset groups

```{r}
sum_prev_sub_dt <- merge_prev_sub_dt %>%
  group_by(case_ind, rounded_DOL, assignment, T1D) %>%
  summarize(assign_rel_abund = mean(assign_rel_abund)) %>%
  ungroup() %>%
  group_by(case_ind, rounded_DOL, assignment) %>%
  filter(n() == 2) %>%
  ungroup()


DOL_merge_prev_sub_wide <- sum_prev_sub_dt %>%
  #group_by(case_ind, rounded_DOL, assignment) %>%
  #filter(n() == 2) %>%
  #ungroup() %>%
  pivot_wider(id_cols = c(case_ind, rounded_DOL, assignment), 
              names_from = T1D, values_from = assign_rel_abund)
```

```{r}
DOL_prev_pair_wilcox_dt <- DOL_merge_prev_sub_wide %>% 
  group_by(rounded_DOL, assignment) %>%
  do(w = wilcox.test(.$Yes, .$No, data=., paired=TRUE)) %>% 
       summarise(rounded_DOL, assignment, 
                 Wilcox = w$p.value,
                 aster = case_when(Wilcox < 0.0001 ~ "****",
                                   Wilcox < 0.001 ~ "***", 
                                   Wilcox < 0.01 ~ "**",
                                   Wilcox < 0.05 ~ "*",
                                   TRUE ~ "ns"))

sum_prev_sub_wil_dt <- merge(sum_prev_sub_dt, DOL_prev_pair_wilcox_dt, 
                             by = c("rounded_DOL", "assignment"))
```

plot relative abundance of temporal subsets accross day of life
```{r}


sum_prev_sub_wil_dt %>%
  ggplot(aes(T1D, assign_rel_abund)) +
  geom_boxplot(aes(fill = T1D), outlier.shape = NA, alpha = 0.6) +
  geom_point(color="grey20", alpha = 0.5, stroke = 0, size = 0.8) +
  geom_line(aes(group = case_ind), color = "lightgrey", alpha = 0.3) +
  geom_text(data = DOL_prev_pair_wilcox_dt, aes(label = aster), x = "No", y = 0.95) +
  scale_fill_manual(values=c("#8CBEB1", "orangered")) +
  theme_bw() +
  ylim(c(NA,1.05)) +
  facet_grid(assignment~factor(rounded_DOL)) +
  labs(x = "day of life (rounded)", 
       y = "Relative Abundance of Subset")  +
  scale_x_discrete(position = "top") +
  theme(legend.position = "bottom", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(file = sprintf("%s/charts/T1D_day_of_life_temporal_subsets_boxplots_NCCgroups.pdf", find_rstudio_root_file()),
       width = 7, height = 7)
```










