---
title: "random forest stats on Country for virome/bacteriome"
output: html_notebook
---

load packages
```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tibble)
library(tidyr)
library(rprojroot)
library(cowplot)
library(nationalparkcolors)
library(randomForest)
library(caret)
library(foreach)
library(doParallel)
```

set paths and filenames
```{r}
### files
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv", find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv", find_rstudio_root_file())

```

load/merge tables
```{r}
long_dt <- fread(sprintf("%s", long_table), sep = "\t", header = T) %>%
  mutate(species = gsub(".*s__","s__", lineage ), 
         sampleID = as.character(sampleID),
         kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                           grepl("k__Vir", lineage) ~ "Virus",
                           grepl("k__Ar", lineage) ~ "Archea",
                           grepl("k__Euk", lineage) ~ "Eukaryota",
                           TRUE ~ "other")) %>%
  subset(select = c("rel_abundance", "sampleID", "species", "kingdom"))

meta_dt <- fread(sprintf("%s", metadata_table), sep = ",", header = T) %>%
  select(-V1) %>%
  mutate(Country = case_when(
           country == 1 ~ "USA",
           country == 2 ~ "FIN",
           country == 3 ~ "GER",
           country == 4 ~ "SWE",
           TRUE ~ "other",
         ),
         sample = as.character(sample))

merge_long_dt <- merge(long_dt, meta_dt, by.x = "sampleID", by.y = "sample") %>%
  subset(select = c("rel_abundance", "sampleID", "species", "kingdom", "mask_id", "Country"))

```


make bacteriome into wideform with country and mask_id label
```{r}
wide_bacteriome_dt <- merge_long_dt %>%
  filter(kingdom == "Bacteria") %>%
  group_by(species) %>%
  filter(n_distinct(sampleID) >= 100) %>%
  ungroup() %>%
  select(-kingdom) %>%
  pivot_wider(names_from = species, values_from = rel_abundance, values_fill = 0) %>%
  select(-sampleID)
## the pipe character "|" was causing issues for the random forest 
colnames(wide_bacteriome_dt) <- gsub("\\|", "XX", colnames(wide_bacteriome_dt))
```


run random forest bacteriome
```{r}
## sample rows from 70% of subjects
train_bacteriome <- wide_bacteriome_dt %>% 
  filter(mask_id %in% sample(unique(mask_id), size = 0.7*length(unique(mask_id))))

## list of mask_id's in train set
in_train_bacteriome <- as.vector(train_bacteriome %>% distinct(mask_id))

## make test to only have mask_id's NOT in train
test_bacteriome <- wide_bacteriome_dt %>% 
  filter(!mask_id %in% in_train_bacteriome[1]$mask_id)

train_bacteriome <- as.data.frame(train_bacteriome %>% 
                                    select(-mask_id))
train_bacteriome$Country <- as.factor(train_bacteriome$Country)

test_bacteriome <- as.data.frame(test_bacteriome %>% 
                                    select(-mask_id))
test_bacteriome$Country <- as.factor(test_bacteriome$Country)

?train

registerDoParallel(cores=6)

rfParam <- expand.grid(importance=TRUE)
lambdas <- c(seq(0, 2, length = 3))

rf_model_bac <- train(x = train_bacteriome[,2:ncol(train_bacteriome)], 
                      y = train_bacteriome[,1], 
                      #data = train_bacteriome, 
                      ntree=30, 
                      method="parRF", 
                      mtry = 2)
#rf_model_bac <- randomForest(Country ~., data = train_bacteriome)
#rf_prediction_bac <- predict(rf_model_bac, test_bacteriome, type = "prob")

```










