---
title: "correlate prevalent phage/bacteria by sample "
output: html_notebook
---

load packages
```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(tibble)
library(tidyr)
library(rprojroot)
library(cowplot)
library(nationalparkcolors)

```

set paths and filenames
```{r}
### files
temporal_table=sprintf("%s/intermediate_files/prev_SGBs_cluster_assignments_long_abundance.tsv", 
                       find_rstudio_root_file())
iphop_table=sprintf("%s/data/TGVG_database_v1.1.exemplars.iphop_genus_outputs1.filt.csv",
                    find_rstudio_root_file())
taxonomy_table=sprintf("%s/data/TGVG_database_v1.1.VC_taxonomy_table.csv",
                       find_rstudio_root_file())
long_table=sprintf("%s/data/mp142_TGVG1.1_MPA4_combined_abundance_table_longform1.tsv",
                   find_rstudio_root_file())
metadata_table=sprintf("%s/data/some_teddy_MP142_metadata2.all_samples1.delivery.csv",
                       find_rstudio_root_file())
vir_info_table=sprintf("%s/data/Marker-MAGu_virus_DB_v1.1_metadata.tsv",
                       find_rstudio_root_file())
```

load long table
```{r}
long_dt <- fread(long_table, sep = "\t", header = T) %>%
  mutate(species = gsub(".*s__","s__", lineage ), 
         genus = gsub(".*g__","g__", lineage ),
         sampleID = as.character(sampleID)) %>%
  mutate(genus = gsub("\\|s__.*", "", genus),
         kingdom = case_when(grepl("k__Bac", lineage) ~ "Bacteria", 
                           grepl("k__Vir", lineage) ~ "Virus",
                           grepl("k__Ar", lineage) ~ "Archea",
                           grepl("k__Euk", lineage) ~ "Eukaryota",
                           TRUE ~ "other")) %>%
  subset(select = c("rel_abundance", "sampleID", "species", "genus", "kingdom"))

prev_ab_dt <- long_dt %>%
  group_by(species) %>%
  ## filter at 100 samples minimum
  filter(n_distinct(sampleID) >= 100) %>%
  ungroup()
```

```{r}
dim(
  prev_ab_dt %>% distinct(species)
)
```


load tables and get host prediction for each virus SGB
```{r}
temporal_dt <- fread(temporal_table, header = T, sep = "\t")

tax_dt <- fread(taxonomy_table, sep = ",", header = T) %>%
  select(c(name, Species))

iphop_dt <- fread(iphop_table, sep = ",", header = T, 
                  col.names = c("name", "AAI", "host_lineage", "confidence", "methods")) %>%
  mutate(host_genus = gsub(".*g__","g__", host_lineage),
         host_family = gsub(";g__.*","", host_lineage))

meta_dt <- fread(metadata_table, sep = ",", header = T) %>%
  select(-V1)

vir_info_dt <- fread(vir_info_table, sep = "\t", header = T) %>%
  mutate(species = gsub(".*s__vSGB","s__vOTU", lineage ))
```


make wide table
```{r}
wide_prev_dt <- prev_ab_dt %>%
  subset( select = c("species", "sampleID", "rel_abundance")) %>%
  distinct() %>%
  pivot_wider(names_from = species, 
              values_from = rel_abundance, 
              values_fill = 0) %>%
  select(-sampleID)
```

correlate viruses and bacteria
```{r}
data_cor <- cor(wide_prev_dt[ , !grepl("vOTU", colnames(wide_prev_dt))],  # Calculate correlations
                wide_prev_dt[ , grepl("vOTU", colnames(wide_prev_dt))])
data_cor <- as.data.frame(data_cor)

data_cor <- setDT(data_cor, keep.rownames = "Bacteria")

cor_long <- data_cor %>%
  pivot_longer(!Bacteria, names_to = "Virus", values_to = "correlation")

cor_long <- setDT(cor_long)
```

```{r}
cor_long %>%
  filter(correlation >= 0.95)
```

add metadata
```{r}

bacteria_genus_dt <- prev_ab_dt %>%
  distinct(species, genus) %>%
  filter(!grepl("__vOTU", species))

merg1_dt <- merge(cor_long, vir_info_dt %>% select(c("species", "Virulence_score", 
                                         "iphop_host_genus")),
      by.x = "Virus", by.y = "species", all.x = T)

merge2_dt <- merge(merg1_dt, bacteria_genus_dt,
                   by.x = "Bacteria", by.y = "species", all.x = T) %>%
  mutate(iphop_host_genus = gsub(".*g__", "g__", iphop_host_genus))
```

```{r}
merge2_dt %>%
  mutate(predict_match = 
           case_when(iphop_host_genus == genus ~ "matching",
                     TRUE ~ "other")) %>%
  arrange(desc(correlation))
```




